### ISSUE TITLE
Fazer tratamento para não inserção de descrição duplicada

### ISSUE THREAD

**Issue by phoenixproject** [gmatozinho/MimAcher#130]
Fazer o tratamento para não inserir registro com descrição duplicada nas Entidades NAC(nome_representante), Área de Atuação(nome), Usuário(e_mail), Campus(local), Ítem(nome) e Participante(nome).

**Comment by phoenixproject** [comment]
O tratamento de nome do representante de NAC não será feito porque nomes podem se repetir.

**Comment by phoenixproject** [comment]
Participante também pode ter o mesmo nome, portanto não será feito este tratamento para ele.

**Comment by phoenixproject** [comment]
O tratamento foi feito, mas depende de verificação de caixa alta e baixa.

**Comment by gmatozinho** [comment]
A verificação tem que ser antes do envio ou é feita no controller?

**Comment by phoenixproject** [comment]
Será feita na camada de infra assim que o controller tentar enviar o dado para o banco de dados.
