### ISSUE TITLE
Alterar o modelo do banco de dados

### ISSUE THREAD

**Issue by phoenixproject** [gmatozinho/MimAcher#72]
Alterar o modelo do banco de dados. Renomear e criar tabelas novas de acordo com o novo modelo.

**Comment by phoenixproject** [comment]
![novo_modelo_bd](https://cloud.githubusercontent.com/assets/1175999/19216455/a447b3d0-8d92-11e6-9721-c5344f84244a.png)

**Comment by phoenixproject** [comment]
Dúvidas:

Por que imagem está como varchar(100) no banco de dados se ela será gravada
no banco? O varchar significa que será gravada em disco e será guardado apenas
o caminho?

O diagrama não permite ver qual o tamanho do campo nome_representante em NAC_CAMPUS

O diagrama também não permite saber se os campus são ou não not null

O campo cod_nac dentro da tabela NAC_AREA_ATUACAO pode ter ter o nome alterado para o mesmo nome da chave primária da tabela NAC_CAMPUS? Porque na tabela PARTICIPANTE ele leva esse nome. O mesmo vale para o campo cod_areaatuacao.

Vou continuar colocando o prefixo MA_ antes do nome de cada tabela, pode ser?


- Posso refazer este diagrama de banco para que ele torne visível tais informações?

**Comment by gmatozinho** [comment]
Por que imagem está como varchar(100) no banco de dados se ela será gravada
no banco? O varchar significa que será gravada em disco e será guardado apenas
o caminho? **só um valor simbolico já q ainda nao definimos isso**

O diagrama não permite ver qual o tamanho do campo nome_representante em NAC_CAMPUS
**o tamanho é o mesmo que para nome na tabela participante**

O diagrama também não permite saber se os campus são ou não not null
**creio que sim pois teremos pelomenos o campus serra pre cadastrado, e o participante e o nac devem ter vinculo com algum campus**

O campo cod_nac dentro da tabela NAC_AREA_ATUACAO pode ter ter o nome alterado para o mesmo nome da chave primária da tabela NAC_CAMPUS? Porque na tabela PARTICIPANTE ele leva esse nome. O mesmo vale para o campo cod_areaatuacao. **pode sim, foi uma falha minha na verdade, inclusive o codigo da area atuação também deve ser renomeado**

Vou continuar colocando o prefixo MA_ antes do nome de cada tabela, pode ser? **pode**

Posso refazer este diagrama de banco para que ele torne visível tais informações? **se possivel sim ira ajudar muito**

**Comment by phoenixproject** [comment]
Novo diagrama incluído em formatos png e pdfs dentro do diretório de Infra.
